config_dicts :
  model:
    class: MultiLayerPerceptron
    layer_sizes: [11, 50, 1]
    activation_function: ReLU
  loss:
    class: MSELoss
  dataset:
    class: UCI_Wine
    normalise_inputs: True
    normalise_outputs: True
  network_weight:
    class: SGD
    lr: -3.0
    weight_decay: -16.0
    momentum: 0.5

network_weight_steps: 10
hyperparameter_steps: 400
validation_proportion: 0.2  # 288/1439
device: cuda
batch_size: 1439
transformed_hyperparameters:
  lr: 10^
  weight_decay: 10^
  momentum: sigmoid
hyperparameter_clipping:
  lr: [-10.0, 0.0]
